org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

maven_group=com.terraformersmc
archive_name=modmenu
mod_id=modmenu
mod_name=Mod Menu
mod_version=26.2-neoforge
mod_license=MIT
mod_authors=TerraformersMC
mod_description=A menu for viewing the list of installed mods.

minecraft_version=26.2
minecraft_version_range=[26.2,)
neo_version=26.2.0.79
neo_version_range=[26.2,)
loader_version_range=[4,)
